name:                 connect4
version:              0.1.0.0
visibility:           public
id:                   connect4-0.1.0.0-kUkhJ1G7nI5QiK0T8ijFM
key:                  connect4-0.1.0.0-kUkhJ1G7nI5QiK0T8ijFM
license:              BSD-3-Clause
copyright:            2023 Author name here
maintainer:           example@example.com
author:               Author name here
homepage:             https://github.com/githubuser/connect4#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/connect4#readme>

abi:                  7862910031cbe2d826c67ef91282d26b
exposed:              True
exposed-modules:      Game Lib Render
hidden-modules:       Paths_connect4
import-dirs:
    /Users/alexmark/Documents/Uni/Y4/FP/Functional-Programming-Assessed-Exercise2023/.stack-work/install/x86_64-osx/e37c0dc34de006cd5d1cd2053733d8543b73a12f676336d758c526e00a765f36/9.4.7/lib/x86_64-osx-ghc-9.4.7/connect4-0.1.0.0-kUkhJ1G7nI5QiK0T8ijFM

library-dirs:
    /Users/alexmark/Documents/Uni/Y4/FP/Functional-Programming-Assessed-Exercise2023/.stack-work/install/x86_64-osx/e37c0dc34de006cd5d1cd2053733d8543b73a12f676336d758c526e00a765f36/9.4.7/lib/x86_64-osx-ghc-9.4.7/connect4-0.1.0.0-kUkhJ1G7nI5QiK0T8ijFM

library-dirs-static:
    /Users/alexmark/Documents/Uni/Y4/FP/Functional-Programming-Assessed-Exercise2023/.stack-work/install/x86_64-osx/e37c0dc34de006cd5d1cd2053733d8543b73a12f676336d758c526e00a765f36/9.4.7/lib/x86_64-osx-ghc-9.4.7/connect4-0.1.0.0-kUkhJ1G7nI5QiK0T8ijFM

dynamic-library-dirs:
    /Users/alexmark/Documents/Uni/Y4/FP/Functional-Programming-Assessed-Exercise2023/.stack-work/install/x86_64-osx/e37c0dc34de006cd5d1cd2053733d8543b73a12f676336d758c526e00a765f36/9.4.7/lib/x86_64-osx-ghc-9.4.7

data-dir:
    /Users/alexmark/Documents/Uni/Y4/FP/Functional-Programming-Assessed-Exercise2023/.stack-work/install/x86_64-osx/e37c0dc34de006cd5d1cd2053733d8543b73a12f676336d758c526e00a765f36/9.4.7/share/x86_64-osx-ghc-9.4.7/connect4-0.1.0.0

hs-libraries:         HSconnect4-0.1.0.0-kUkhJ1G7nI5QiK0T8ijFM
depends:
    base-4.17.2.0 gloss-1.13.2.2-KVSA5cbB3FhGSnBBB6gZFS
    optparse-applicative-0.17.1.0-JGd5MH5XQ0j64JO3zvXWDD

haddock-interfaces:
    /Users/alexmark/Documents/Uni/Y4/FP/Functional-Programming-Assessed-Exercise2023/.stack-work/install/x86_64-osx/e37c0dc34de006cd5d1cd2053733d8543b73a12f676336d758c526e00a765f36/9.4.7/doc/connect4-0.1.0.0/connect4.haddock

haddock-html:
    /Users/alexmark/Documents/Uni/Y4/FP/Functional-Programming-Assessed-Exercise2023/.stack-work/install/x86_64-osx/e37c0dc34de006cd5d1cd2053733d8543b73a12f676336d758c526e00a765f36/9.4.7/doc/connect4-0.1.0.0
